server:
  port: 8080
spring:
  application:
    name: "sigecbluebank"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  region: "us-east-1"
  secretName: "my-secret"
